# Generated by Django 5.0.1 on 2024-01-20 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_demandcontent_geographycontent_skillscontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandcontent',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.image'),
        ),
        migrations.AddField(
            model_name='geographycontent',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.image'),
        ),
        migrations.AddField(
            model_name='skillscontent',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.image'),
        ),
    ]
