# Generated by Django 5.0.1 on 2024-01-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_demandcontent_image_geographycontent_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandcontent',
            name='content',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='geographycontent',
            name='content',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='skillscontent',
            name='content',
            field=models.JSONField(null=True),
        ),
    ]
