# Generated by Django 5.0.1 on 2024-01-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_demandcontent_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandcontent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='geographycontent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='skillscontent',
            name='image',
        ),
        migrations.AddField(
            model_name='demandcontent',
            name='graphic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='geographycontent',
            name='graphic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='skillscontent',
            name='graphic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
