# Generated by Django 5.0.1 on 2024-01-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_skillsyear_remove_skillscontent_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillscontent',
            name='graphics',
        ),
        migrations.AddField(
            model_name='skillsyear',
            name='skills_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.skillscontent'),
        ),
    ]
